### ISSUE TITLE
Suggestions from Uruguay Oct 30

### ISSUE THREAD

**Issue by dicook** [KrisanatA/animbook#13]
- [x] Speed for the kangaroo plot should have a good default, and an example in the code of how to change it
- [x] The default for the wallaby_plot should be time_dependent = FALSE
- [x] Able to add labels of start and end time on wallaby_plot

**Comment by dicook** [comment]
- [ ] There might be a bug in the kangaroo_plot() in the points that get drawn between bars

**Comment by KrisanatA** [comment]
- [ ] Check for the object in the anim_animate()
- [ ] Add the messages instruction for what is the next step
